name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  export-windows:
    name: Export for Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Export Godot Game
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          # The export preset is named "Windows Desktop" in export_presets.cfg
          export_preset: "Windows Desktop"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.export.outputs.archive_directory }}/*
          generate_release_notes: true
